name: Build and Deploy Next.js Application to VPS - react-menu-app

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_KEY }}

      - name: Add VPS Host to Known Hosts
        run: |
          ssh-keyscan -p ${{ secrets.VPS_PORT }} -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh -p ${{ secrets.VPS_PORT }} -T ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            set -euo pipefail
            echo "Starting deployment..."
            
            # Navegar até o diretório do projeto
            cd ${{ secrets.VPS_PATH }}

            # Atualizar o repositório com a última versão da branch main
            echo "Pulling latest changes from repository..."
            git fetch origin
            git reset --hard origin/main

            # Instalar dependências e construir o projeto
            echo "Installing dependencies and building the project..."
            yarn install --frozen-lockfile
            yarn build

            # Reiniciar a aplicação com PM2
            echo "Starting or restarting application with PM2..."
            pm2 startOrRestart ~/ecosystem.config.js

            echo "Deployment completed successfully!"
          EOF
